In [39]:
import numpy as np
import pandas as pd

V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])

df = pd.DataFrame({'V1': V1, 'V2': V2, 'V3': V3})

df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [14]:
from sklearn import preprocessing

In [15]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [16]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

In [17]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))

In [18]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

In [19]:
binarizer = preprocessing.Binarizer(threshold = 5).fit(df)

In [20]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [21]:
import seaborn as sns
tips = sns.load_dataset('tips')
df_l = tips.copy()
df_l.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df_l['yeni_sex'] = df_l['sex'].cat.codes

In [23]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         0
2       21.01  3.50    Male     No  Sun  Dinner     3         0
3       23.68  3.31    Male     No  Sun  Dinner     2         0
4       24.59  3.61  Female     No  Sun  Dinner     4         1

In [24]:
lbe = preprocessing.LabelEncoder()

In [25]:
df_l['daha_yeni_sex'] = lbe.fit_transform(df_l['sex'])

In [26]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

In [27]:
df.head()

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [28]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

In [29]:
df_l['yeni_gun'] = np.where(df_l['day'].str.contains('Sun'),1,0)

In [31]:
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  yeni_sex  \
0        16.99  1.01  Female     No  Sun  Dinner     2         1   
1        10.34  1.66    Male     No  Sun  Dinner     3         0   
2        21.01  3.50    Male     No  Sun  Dinner     3         0   
3        23.68  3.31    Male     No  Sun  Dinner     2         0   
4        24.59  3.61  Female     No  Sun  Dinner     4         1   
5        25.29  4.71    Male     No  Sun  Dinner     4         0   
6         8.77  2.00    Male     No  Sun  Dinner     2         0   
7        26.88  3.12    Male     No  Sun  Dinner     4         0   
8        15.04  1.96    Male     No  Sun  Dinner     2         0   
9        14.78  3.23    Male     No  Sun  Dinner     2         0   
10       10.27  1.71    Male     No  Sun  Dinner     2         0   
11       35.26  5.00  Female     No  Sun  Dinner     4         1   
12       15.42  1.57    Male     No  Sun  Dinner     2         0   
13       18.43  3.00    Male     No  Sun  Dinner     4         0   
14       14.83  3.02  Female     No  Sun  Dinner     2         1   
15       21.58  3.92    Male     No  Sun  Dinner     2         0   
16       10.33  1.67  Female     No  Sun  Dinner     3         1   
17       16.29  3.71    Male     No  Sun  Dinner     3         0   
18       16.97  3.50  Female     No  Sun  Dinner     3         1   
19       20.65  3.35    Male     No  Sat  Dinner     3         0   

    daha_yeni_sex  yeni_gun  
0               0         1  
1               1         1  
2               1         1  
3               1         1  
4               0         1  
5               1         1  
6               1         1  
7               1         1  
8               1         1  
9               1         1  
10              1         1  
11              0         1  
12              1         1  
13              1         1  
14              0         1  
15              1         1  
16              0         1  
17              1         1  
18              0         1  
19              1         0

In [32]:
lbe = preprocessing.LabelEncoder()

In [33]:
df_l['daha_yeni_gun'] = lbe.fit_transform(df_l['day'])

In [36]:
df_l

total_bill   tip     sex smoker   day    time  size  yeni_sex  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1   
1         10.34  1.66    Male     No   Sun  Dinner     3         0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1   
..          ...   ...     ...    ...   ...     ...   ...       ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1   

     daha_yeni_sex  yeni_gun  daha_yeni_gun  
0                0         1              2  
1                1         1              2  
2                1         1              2  
3                1         1              2  
4                0         1              2  
..             ...       ...            ...  
239              1         0              1  
240              0         0              1  
241              1         0              1  
242              1         0              1  
243              0         0              3  

[244 rows x 11 columns]

In [41]:
df_one_hot = df_l.copy()

In [42]:
pd.get_dummies(df_one_hot, columns = ['sex'], prefix = ['sex']).head()

total_bill   tip smoker  day    time  size  yeni_sex  daha_yeni_sex  \
0       16.99  1.01     No  Sun  Dinner     2         1              0   
1       10.34  1.66     No  Sun  Dinner     3         0              1   
2       21.01  3.50     No  Sun  Dinner     3         0              1   
3       23.68  3.31     No  Sun  Dinner     2         0              1   
4       24.59  3.61     No  Sun  Dinner     4         1              0   

   yeni_gun  daha_yeni_gun  sex_Male  sex_Female  
0         1              2         0           1  
1         1              2         1           0  
2         1              2         1           0  
3         1              2         1           0  
4         1              2         0           1

In [43]:
import seaborn as sns
tips = sns.load_dataset('tips')
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [44]:
dff = df.select_dtypes(include = ['float64', 'int64'])

In [46]:
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], encode='ordinal', strategy='quantile').fit(dff)

In [47]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [48]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [49]:
df['yeni_degisken'] = df.index

In [50]:
df

total_bill   tip     sex smoker   day    time  size  yeni_degisken
0         16.99  1.01  Female     No   Sun  Dinner     2              0
1         10.34  1.66    Male     No   Sun  Dinner     3              1
2         21.01  3.50    Male     No   Sun  Dinner     3              2
3         23.68  3.31    Male     No   Sun  Dinner     2              3
4         24.59  3.61  Female     No   Sun  Dinner     4              4
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3            239
240       27.18  2.00  Female    Yes   Sat  Dinner     2            240
241       22.67  2.00    Male    Yes   Sat  Dinner     2            241
242       17.82  1.75    Male     No   Sat  Dinner     2            242
243       18.78  3.00  Female     No  Thur  Dinner     2            243

[244 rows x 8 columns]

In [51]:
df['yeni_degisken'] = df['yeni_degisken'] + 10

In [52]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2             10
1       10.34  1.66    Male     No  Sun  Dinner     3             11
2       21.01  3.50    Male     No  Sun  Dinner     3             12
3       23.68  3.31    Male     No  Sun  Dinner     2             13
4       24.59  3.61  Female     No  Sun  Dinner     4             14