In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13], dtype = 'int')

array([ 3,  4,  2, 13])

In [8]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5), dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [13]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(3,4))

array([[12.87908851, 16.06085153, 11.18558389, 13.28184994],
       [ 8.32088858,  4.82510142, 20.54477188,  4.74832285],
       [ 8.85878373,  9.12784313,  7.14666696, 14.1106939 ]])

In [16]:
np.random.randint(0,10,(3,3))

array([[9, 5, 4],
       [9, 1, 4],
       [9, 8, 7]])