In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [10]:
m = np.random.normal(20,5, (3,3))

In [11]:
m

array([[22.83336204, 21.22261506, 15.83657299],
       [28.59054948, 23.68446301, 23.21954301],
       [26.06927746, 16.13380276, 24.43441096]])

In [12]:
np.sort(m, axis=1)

array([[15.83657299, 21.22261506, 22.83336204],
       [23.21954301, 23.68446301, 28.59054948],
       [16.13380276, 24.43441096, 26.06927746]])

In [13]:
np.sort(m, axis=0)

array([[22.83336204, 16.13380276, 15.83657299],
       [26.06927746, 21.22261506, 23.21954301],
       [28.59054948, 23.68446301, 24.43441096]])