In [3]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([6, 0, 6, 9, 5, 9, 6, 5, 4, 5])

In [4]:
a[0]

6

In [5]:
a[-1]

5

In [6]:
a[0] = 100

In [7]:
a

array([100,   0,   6,   9,   5,   9,   6,   5,   4,   5])

In [8]:
b = np.random.randint(10, size= (3,5))
b

array([[8, 5, 8, 8, 7],
       [0, 8, 8, 9, 9],
       [9, 0, 9, 2, 1]])

In [9]:
b[0][0]

8

In [10]:
b[0][1]

5

In [11]:
b[2][3]

2

In [12]:
b[2,3]

2

In [13]:
b[2,3] = 99

In [14]:
b

array([[ 8,  5,  8,  8,  7],
       [ 0,  8,  8,  9,  9],
       [ 9,  0,  9, 99,  1]])

In [15]:
b[2,3] = 2.7

In [16]:
b

array([[8, 5, 8, 8, 7],
       [0, 8, 8, 9, 9],
       [9, 0, 9, 2, 1]])