In [1]:
import numpy as np

5*x0 + x1 = 12              
x0 + 3*x1 = 10

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [4]:
a

array([[5, 1],
       [1, 3]])

In [5]:
b

array([12, 10])

In [7]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

In [8]:
c = np.array([[5,1], [1,3]])
d = np.array([38,16])

In [9]:
c

array([[5, 1],
       [1, 3]])

In [10]:
d

array([38, 16])

In [12]:
x = np.linalg.solve(c,d)
x

array([7., 3.])