In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[::2]

array([20, 22, 24, 26, 28])

In [8]:
a[1::3]

array([21, 24, 27])

In [9]:
m = np.random.randint(10, size=(5,5))

In [10]:
m

array([[4, 1, 3, 2, 1],
       [9, 4, 5, 3, 3],
       [8, 9, 7, 7, 4],
       [1, 2, 9, 1, 0],
       [6, 4, 6, 1, 9]])

In [11]:
m[:,0]

array([4, 9, 8, 1, 6])

In [12]:
m[:,1]

array([1, 4, 9, 2, 4])

In [13]:
m[0,:]

array([4, 1, 3, 2, 1])

In [14]:
m[1,:]

array([9, 4, 5, 3, 3])

In [15]:
m[2:,3]

array([7, 1, 1])

In [16]:
m[0:2, 0:3]

array([[4, 1, 3],
       [9, 4, 5]])

In [18]:
m[:,:2]

array([[4, 1],
       [9, 4],
       [8, 9],
       [1, 2],
       [6, 4]])

In [19]:
m[1:3, 0:2]

array([[9, 4],
       [8, 9]])