In [2]:
import numpy as np
a = np.random.randint(10, size=(5,5))
a

array([[7, 5, 1, 7, 2],
       [0, 9, 0, 0, 9],
       [3, 7, 2, 0, 7],
       [9, 5, 9, 9, 0],
       [2, 2, 0, 1, 9]])

In [3]:
alt_a = a[0:3, 0:2]
alt_a

array([[7, 5],
       [0, 9],
       [3, 7]])

In [4]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [5]:
alt_a

array([[99999,     5],
       [    0,   888],
       [    3,     7]])

In [6]:
a

array([[99999,     5,     1,     7,     2],
       [    0,   888,     0,     0,     9],
       [    3,     7,     2,     0,     7],
       [    9,     5,     9,     9,     0],
       [    2,     2,     0,     1,     9]])

In [7]:
a = np.random.randint(10, size=(5,5))
a

array([[8, 9, 9, 4, 2],
       [3, 9, 4, 4, 6],
       [2, 3, 4, 5, 1],
       [0, 2, 3, 0, 9],
       [7, 1, 4, 5, 8]])

In [9]:
alt_b = a[0:3, 0:2].copy()
alt_b

array([[8, 9],
       [3, 9],
       [2, 3]])

In [10]:
alt_b[0,0] = 9999
alt_b

array([[9999,    9],
       [   3,    9],
       [   2,    3]])

In [11]:
a

array([[8, 9, 9, 4, 2],
       [3, 9, 4, 4, 6],
       [2, 3, 4, 5, 1],
       [0, 2, 3, 0, 9],
       [7, 1, 4, 5, 8]])