In [1]:
import numpy as np
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [2]:
v - 1

array([0, 1, 2, 3, 4])

In [3]:
v * 5

array([ 5, 10, 15, 20, 25])

In [4]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [5]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [7]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [8]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [10]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [12]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [13]:
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [15]:
v % 2

array([1, 0, 1, 0, 1])

In [16]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [17]:
np.absolute(np.array([-3]))

array([3])

In [18]:
np.sin(360)

0.9589157234143065

In [19]:
np.cos(180)

-0.5984600690578581

In [20]:
k = np.array([1,2,3])

In [21]:
np.log(k)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.log2(k)

array([0.       , 1.       , 1.5849625])

In [23]:
np.log10(k)

array([0.        , 0.30103   , 0.47712125])

In [24]:
?np

Type:        module
String form: <module 'numpy' from '/Users/ardahanaytan/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>
File:        ~/anaconda3/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 4

In [25]:
np.mean(v)

3.0

In [26]:
v.sum()

15

In [27]:
v.min()

1

In [28]:
v.max()

5